# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - '*'

variables:
  isMain: $[eq(variables['Build.SourceBranchName'], 'main')]
  isHotfix: $[startsWith(variables['Build.SourceBranchName'], 'hotfix')]
  isCandidate: $[startsWith(variables['Build.SourceBranchName'], 'rc-')]
  isRelease: $[startsWith(variables['Build.SourceBranchName'], 'v')]

stages:
- stage: Build
  pool: Default
  jobs: 
  - job: Initialize
    steps:
    - script: |
        GIT_SHA=$(git rev-parse --short HEAD)
        echo "##vso[task.setvariable variable=GIT_SHA;]$GIT_SHA"
        GIT_TAG=$(git tag --points-at HEAD)
        echo "##vso[task.setvariable variable=GIT_TAG;]$GIT_TAG"
        echo "isMain : $(isMain)"
        echo "isHotfix: $(isHotfix)"
        echo "isCandidate : $(isCandidate)"
        echo "isRelease: $(isRelease)"
        echo "GIT_TAG: $GIT_TAG"
        echo "GIT_SHA: $GIT_SHA"
      displayName: 'Set ENV variables'
  - job: Build
    condition: or(eq(variables.isMain,true),eq(variables.isHotfix,true))
    steps:
    - script: |
        echo "Building code for $GIT_SHA"
        echo "image name: $(Build.Repository.Name):$GIT_SHA"
      displayName: 'Build'
- stage: Deploy_Dev
  condition: eq(variables.isMain,true)
  pool: Default
  jobs:
  - job: Deploy_Dev
    steps:
    - script: |
        echo "deploying to dev"
      displayName: 'Deploy to dev'
- stage: Deploy_SAND
  pool: Default
  condition: eq(variables.isCandidate,true)
  jobs:
  - job: Deploy_SAND
    steps:
    - script: |
        echo "docker pull image:$GIT_SHA"
        echo "docker tag image:$GIT_TAG"
        echo "deploying to SAND"
      displayName: 'Deploy to SAND'
- stage: Deploy_Prod
  condition: eq(variables.isRelease,true)
  pool: Default
  jobs:
  - job: Deploy_Prod
    steps:
    - script: |
        echo "docker pull image:$GIT_SHA"
        echo "docker tag image:$GIT_TAG"
        echo "deploying to Prod"
      displayName: 'Deploy to Prod'