# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - hotfix*
  tags:
    include:
      - '*'
pr: none

variables:
  isMain: $[eq(variables['Build.SourceBranchName'], 'main')]
  isHotfix: $[startsWith(variables['Build.SourceBranchName'], 'hotfix')]
  isCandidate: $[startsWith(variables['Build.SourceBranchName'], 'rc-')]
  isRelease: $[startsWith(variables['Build.SourceBranchName'], 'v')]

stages:
- stage: Build
  pool: Default
  jobs: 
  - job: Initialize
    steps:
    - task: Bash@3
      displayName: 'Set ENV variables'
      inputs:
        targetType: inline
        script: |
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "##vso[task.setvariable variable=gitSHA;]$GIT_SHA"

          # Get the tag pointing to the current commit
          GIT_TAG=$(git tag --points-at HEAD)
          echo "##vso[task.setvariable variable=gitTAG;]$GIT_TAG"
          echo "isMain : $(isMain)"
          echo "isHotfix: $(isHotfix)"
          echo "isCandidate : $(isCandidate)"
          echo "isRelease: $(isRelease)"
          echo "GIT_TAG: $gitSHA"
          echo "GIT_SHA: $gitTAG"
  - job: Build
    condition: or(eq(variables.isMain,true),eq(variables.isHotfix,true))
    steps:
    - script: |
        echo "Building code for $(gitSHA)"
        echo "image name: $(Build.Repository.Name):$(gitSHA)"
      displayName: 'Build'
- stage: Deploy_Dev
  condition: eq(variables.isMain,true)
  pool: Default
  jobs:
  - job: Deploy_Dev
    steps:
    - script: |
        echo "deploying to dev"
      displayName: 'Deploy to dev'
- stage: Deploy_SAND
  pool: Default
  condition: eq(variables.isCandidate,true)
  jobs:
  - job: Deploy_SAND
    steps:
    - script: |
        echo "docker pull image:$gitSHA"
        echo "docker tag image:$gitTAG"
        echo "deploying to SAND"
      displayName: 'Deploy to SAND'
- stage: Deploy_Prod
  condition: eq(variables.isRelease,true)
  pool: Default
  jobs:
  - job: Deploy_Prod
    steps:
    - script: |
        echo "docker pull image:$gitSHA"
        echo "docker tag image:$gitTAG"
        echo "deploying to Prod"
      displayName: 'Deploy to Prod'