# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - hotfix*
  tags:
    include:
      - '*'
# trigger: none
pr: none

variables:
  isMain: $[eq(variables['Build.SourceBranchName'], 'main')]
  isHotfix: $[startsWith(variables['Build.SourceBranchName'], 'hotfix')]
  isCandidate: $[startsWith(variables['Build.SourceBranchName'], 'rc-')]
  isRelease: $[startsWith(variables['Build.SourceBranchName'], 'v')]
  IMAGE: $(Build.Repository.Name)
stages:
- stage: build
  condition: or(eq(variables.isMain,true),eq(variables.isHotfix,true))
  variables:
    GIT_SHA: $[ stageDependencies.setup.init.outputs['set_env.sha'] ]
    GIT_TAG: $[ stageDependencies.setup.init.outputs['set_env.tag'] ]
  jobs:
  - job: Build
    pool: 'Default'
    steps:
    - task: Bash@3
      name: set_env
      displayName: 'Set Env'
      inputs:
        targetType: inline
        script: |
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "##vso[task.setvariable variable=sha]$GIT_SHA"
          echo $GIT_SHA
          GIT_TAG=$(git tag --points-at HEAD)
          echo "##vso[task.setvariable variable=tag]$GIT_TAG"
          echo $GIT_TAG
    - script: |
        echo "Building code for $(sha)"
        echo "image name: $(IMAGE):$(sha)"
        echo $(sha)
        echo $(tag)
      displayName: 'Build'

- stage: deploy_dev
  condition: eq(variables.isMain,true)
  displayName: 'Deploy to Dev'
  dependsOn: 'build'
  jobs:
  - deployment:
    pool: 'Default' #Replace with Dev Agent pool
    environment: development
    displayName: 'Deploy to dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              name: set_env
              displayName: 'Set Env'
              inputs:
                targetType: inline
                script: |
                  GIT_SHA=$(git rev-parse --short HEAD)
                  echo "##vso[task.setvariable variable=sha]$GIT_SHA"
                  echo $GIT_SHA
                  GIT_TAG=$(git tag --points-at HEAD)
                  echo "##vso[task.setvariable variable=tag]$GIT_TAG"
                  echo $GIT_TAG
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  echo "container app dev deployment with DEV_ACR/$(IMAGE):$(sha)"
- stage: deploy_sand
  condition: eq(variables.isCandidate,true)
  displayName: 'Deploy to sand'
  jobs:
  - deployment:
    pool: 'Default' #Replace with Sand US Agent pool
    environment: sandbox_US
    displayName: 'Deploy to sand US'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              name: set_env
              displayName: 'Set Env'
              inputs:
                targetType: inline
                script: |
                  GIT_SHA=$(git rev-parse --short HEAD)
                  echo "##vso[task.setvariable variable=sha]$GIT_SHA"
                  echo $GIT_SHA
                  GIT_TAG=$(Build.SourceBranchVersion)
                  echo "##vso[task.setvariable variable=tag]$GIT_TAG"
                  echo $GIT_TAG
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  echo "docker pull $(IMAGE):$(sha)"
                  echo "docker tag $(IMAGE):$(sha) $(IMAGE):$(tag)"
                  echo "docker push SAND_ACR/$(IMAGE):$(tag)"
                  echo "container app dev deployment with SAND_ACR/$(IMAGE):$(tag)"
  - deployment:
    pool: 'Default' #Replace with Sand UK Agent pool
    environment: sandbox_UK
    displayName: 'Deploy to sand UK'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              name: set_env
              displayName: 'Set Env'
              inputs:
                targetType: inline
                script: |
                  GIT_SHA=$(git rev-parse --short HEAD)
                  echo "##vso[task.setvariable variable=sha]$GIT_SHA"
                  echo $GIT_SHA
                  GIT_TAG=$(git tag --points-at HEAD)
                  echo "##vso[task.setvariable variable=tag]$GIT_TAG"
                  echo $GIT_TAG
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  echo "docker pull $(IMAGE):$(sha)"
                  echo "docker tag $(IMAGE):$(sha) $(IMAGE):$(tag)"
                  echo "docker push SAND_ACR/$(IMAGE):$(tag)"
                  echo "container app sand deployment with SAND_UK_ACR/$(IMAGE):$(tag)"

- stage: deploy_prod
  condition: eq(variables.isRelease,true)
  displayName: 'Deploy to Prod'
  jobs:
  - deployment:
    pool: 'Default' #Replace with Dev Agent pool
    environment: production
    displayName: 'Deploy to prod'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              name: set_env
              displayName: 'Set Env'
              inputs:
                targetType: inline
                script: |
                  GIT_SHA=$(git rev-parse --short HEAD)
                  echo "##vso[task.setvariable variable=sha]$GIT_SHA"
                  echo $GIT_SHA
                  GIT_TAG=$(git tag --points-at HEAD)
                  echo "##vso[task.setvariable variable=tag]$GIT_TAG"
                  echo $GIT_TAG
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  echo "docker pull $(IMAGE):$(sha)"
                  echo "docker tag $(IMAGE):$(sha) $(IMAGE):$(tag)"
                  echo "docker push SAND_ACR/$(IMAGE):$(tag)"
                  echo "container app prod deployment with PROD_ACR/$(IMAGE):$(tag)"